import Head from 'next/head'
import { Inter } from '@next/font/google'
import Inicio from '@/components/Inicio'
import Corta from '@/components/Corta'
import CortaF from '@/components/CortaF'
import Conteudo from '@/components/Conteudo'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='flex flex-col justify-center items-center'>
      <Head>
        <title>Marcelo Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Inicio />
      <Conteudo />
      <Footer />
    </div>
  )
}
